version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: todos-mariadb-server
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=todos_user
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/laravel:9
    container_name: todos-laravel-server
    ports:
      - '8001:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=todos_user
      - DB_DATABASE=bitnami_myapp
    volumes:
      - './todos-project:/app'
    depends_on:
      - mariadb